# Generated by Django 5.1.4 on 2024-12-17 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('price_range', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment', models.JSONField(blank=True, null=True)),
                ('trainers', models.JSONField(blank=True, null=True)),
                ('subscription_pricing', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField()),
                ('membership_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='facilities.gym')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
