# Generated by Django 5.1.4 on 2024-12-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_gym_member_delete_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
