# Generated by Django 5.1.4 on 2024-12-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_gym_latitude_gym_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gym_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='facilities.gym')),
            ],
        ),
    ]
