# Generated by Django 5.1.4 on 2024-12-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_alter_gymmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.JSONField(),
        ),
    ]
