# Generated by Django 5.1.4 on 2024-12-19 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_alter_gym_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='trainers',
        ),
        migrations.AlterField(
            model_name='gymtrainer',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='facilities.gym'),
        ),
    ]
