# Generated by Django 5.1.4 on 2024-12-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_remove_gym_trainers_alter_gymtrainer_gym'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gym',
            name='subscription_pricing',
        ),
        migrations.CreateModel(
            name='GymSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.ManyToManyField(to='facilities.gymfeature')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='facilities.gym')),
            ],
        ),
    ]
