# Generated by Django 5.1.4 on 2024-12-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_gymfeature_remove_gym_subscription_pricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymsubscriptionplan',
            name='offers',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
