# Generated by Django 5.1.4 on 2024-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_gymsubscriptionplan_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='description',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gym_logos/'),
        ),
    ]
