# Generated by Django 5.1.4 on 2024-12-19 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0012_gym_average_rating_gym_review_count_gymratingreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymratingreview',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
