# Generated by Django 5.1.4 on 2024-12-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0013_alter_gymratingreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='subscription_plan_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gym_members', to='facilities.gymsubscriptionplan'),
        ),
        migrations.AddField(
            model_name='gymphoto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gym_videos/'),
        ),
        migrations.AlterField(
            model_name='gymratingreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
