# Generated by Django 5.1.4 on 2024-12-22 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0014_gymmember_subscription_plan_new_gymphoto_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gymmember',
            unique_together={('user', 'gym')},
        ),
        migrations.AlterUniqueTogether(
            name='gymtrainer',
            unique_together={('user', 'gym')},
        ),
    ]
