# Generated by Django 5.1.4 on 2024-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0015_alter_gymmember_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmember',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gymsubscriptionplan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gymtrainer',
            name='id',
        ),
        migrations.AddField(
            model_name='gymmember',
            name='gym_member_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymsubscriptionplan',
            name='gym_subscription_plan_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymtrainer',
            name='gym_trainer_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
