# Generated by Django 5.1.4 on 2024-12-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0016_remove_gymmember_id_remove_gymsubscriptionplan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmember',
            name='gym_member_id',
        ),
        migrations.RemoveField(
            model_name='gymsubscriptionplan',
            name='gym_subscription_plan_id',
        ),
        migrations.RemoveField(
            model_name='gymtrainer',
            name='gym_trainer_id',
        ),
        migrations.AddField(
            model_name='gymmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymsubscriptionplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymtrainer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
