# Generated by Django 5.1.4 on 2024-12-29 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0018_alter_gymmember_user_alter_gymtrainer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymphoto',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='gym',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gym',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gymfeature',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_features_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymfeature',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymfeature',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_features_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_member_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='gymmember',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_member_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gymphoto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_photos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='gymphoto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_photos_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymratingreview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_reviews_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymratingreview',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_reviews_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymsubscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gymsubscriptionplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_subscription_plans_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymsubscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='gymsubscriptionplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_subscription_plans_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymtrainer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gymtrainer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_trainer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymtrainer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='gymtrainer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_trainer_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gym',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymratingreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymratingreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
