# Generated by Django 5.1.4 on 2024-12-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0019_remove_gymphoto_uploaded_at_gym_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='price_range',
        ),
        migrations.AddField(
            model_name='gym',
            name='standard',
            field=models.CharField(blank=True, choices=[('basid', 'basic'), ('standard', 'standard'), ('premium', 'premium')], null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymfeature',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='gym_features/'),
        ),
        migrations.AddField(
            model_name='gymfeature',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='gym_features/'),
        ),
        migrations.AddField(
            model_name='gymphoto',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
