# Generated by Django 5.1.4 on 2024-12-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0020_remove_gym_price_range_gym_standard_gym_website_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymphoto',
            old_name='category',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='gymphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gym_photos/'),
        ),
    ]
